### ISSUE TITLE
pibox fork of ansiblecube

### ISSUE THREAD

**Issue by gui1117** [ideascube/ansiblecube#134]
this are the task needed to merge pibox fork of ansiblecube at https://github.com/thiolliere/ansiblecube/tree/oneUpdateFile0.4

* [ ] fix of ideascube version https://github.com/thiolliere/ansiblecube/commit/1a91766befd39d3c2253250c2fda0b4f503b84fb
* [ ]  add of wikifundi https://github.com/thiolliere/ansiblecube/commit/f55170e9f82149d3f04ed0ef7d3fc8055bfe5b6b
* [ ]  add of edupi https://github.com/thiolliere/ansiblecube/commit/4ee8d23410d85cdde9fd4cd1eee1011cbcb94626
* [ ] add of aflatoun  https://github.com/thiolliere/ansiblecube/commit/ea48e2225824e4d1ec62a51c2a1da47cf0e1ccaf
* [ ] remove update procedure #132 
* [ ] replace static suffix with dynamic one #133 
* [ ] hostname issues relative to hostname #130 #131
